version: '3.9'

services:
  main:
    container_name: track-bot
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    env_file: .env
    command: sh -c "npm i && npm run build && npm run start"
    networks:
      - site
    restart: unless-stopped

networks:
  site:
    driver: bridge
    external: true
